# chronicle Makefile — the lifecycle only: help / build / test / lint / ci /
# publish / clean. Anything else is the `fluxor` CLI directly
# (`fluxor modules build`, `fluxor run`, `fluxor update`, `fluxor sync`,
# `fluxor build --check …`) — a make target that merely renames one CLI
# command is bloat, not convenience.
#
# The bodies are gate-enforced character for character by `fluxor ci`'s
# `makefile` phase (../standards/make.md §2). They can be identical across
# projects because the VERB is not: each reads this checkout's shape — no cargo
# crate at all, `modules/` + `[ci].targets`, the declared module harnesses under
# `modules/app/*/tests/`, `[ci.test] scripts` — and does what that shape
# implies. So `make test` here is the module harnesses plus the 22 graph E2Es,
# and `make build` is the PIC module build, with no recipe carrying that
# knowledge.
#
# `make help` is generated by `fluxor help --make`, which walks `tools/` for
# real, so the script list cannot fall behind the tree. The two things it cannot
# know — the one-time `make -C ../fluxor install` bootstrap, and the `protoc`
# invocation that type-checks the canonical artefact schemas as a set — live in
# README.md, which is where a reader without the CLI installed is.

SHELL       := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.DEFAULT_GOAL := build

.PHONY: help build test lint ci publish clean

help:
	@fluxor help --make

build:
	fluxor build

test:
	fluxor test

lint:
	fluxor lint

ci:
	fluxor ci

publish:
	fluxor publish

clean:
	fluxor clean
