#!/usr/bin/env bash
# CHANNEL-HOP REGISTER for the shipping example graphs.
#
# An engine->engine hop is one chronicle engine feeding another directly:
# `pipeline -> decision`, `pipeline -> pipeline`, and so on. Each one costs a
# channel write, a channel read and a scheduler dispatch that a single node
# running both programs would not pay.
#
# It does NOT cost a serialize/deserialize: `pipeline_core` already threads
# frames between its own stages ("serialize-at-the-boundary semantics"), so
# the codec is paid either way. That is the whole reason this metric is a
# COUNT rather than a benchmark — the saving is scheduler and channel work,
# which only a running graph on real hardware can price.
#
# Like `resource-summary.sh` this is generated and diffed, so a graph that
# grows a hop has to say so in the same change.
#
#   tools/ci/hop-count.sh            # --check (CI): fail if the doc is stale
#   tools/ci/hop-count.sh --write    # regenerate
set -u
here="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$here"
mode="${1:---check}"
DOC="docs/architecture/hop_register.md"

gen() {
  echo "# Channel-hop register"
  echo ""
  echo "Generated by \`tools/ci/hop-count.sh\` from \`examples/**/*.yaml\` —"
  echo "do not edit by hand. An engine->engine hop is one chronicle engine"
  echo "(\`pipeline\`, \`decision\`, \`expression\`, \`aggregation\`) feeding another"
  echo "directly: a channel write, a channel read and a scheduler dispatch that"
  echo "one node running both programs would not pay. The codec is NOT part of"
  echo "the saving — stages serialize between themselves inside a node too."
  echo ""
  echo "| Graph | Nodes | Wires | Engine->engine hops |"
  echo "|---|---|---|---|"
  python3 - <<'PY'
import re, pathlib
ENG = {'pipeline', 'decision', 'expression', 'aggregation'}
rows = []
for y in sorted(pathlib.Path('examples').rglob('*.yaml')):
    t = y.read_text()
    types = {}
    for nm, ty in re.findall(r'^\s*-\s*name:\s*(\S+)\s*$(?:\n\s+type:\s*(\S+))?', t, re.M):
        types[nm] = ty or nm
    hops = re.findall(r'-\s*from:\s*(\w+)\.\w+\s*\n\s*to:\s*(\w+)\.\w+', t)
    eng = [(a, b) for a, b in hops if types.get(a) in ENG and types.get(b) in ENG]
    rows.append((str(y), len(types), len(hops), len(eng)))
for path, n, w, e in rows:
    print(f"| `{path}` | {n} | {w} | {e} |")
print()
print(f"**Total engine->engine hops: {sum(r[3] for r in rows)}**")
PY
}

if [ "$mode" = "--check" ]; then
  tmp=$(mktemp)
  gen > "$tmp"
  if ! diff -q "$tmp" "$DOC" >/dev/null 2>&1; then
    echo "  FAIL  hop-count: $DOC is stale — run tools/ci/hop-count.sh --write"
    diff "$DOC" "$tmp" 2>/dev/null | head -20
    rm -f "$tmp"; exit 1
  fi
  rm -f "$tmp"
  echo "  PASS  hop-count: $DOC matches the graphs"
else
  mkdir -p "$(dirname "$DOC")"
  gen > "$DOC"
  echo "  wrote $DOC"
fi
