#!/usr/bin/env bash
# Resource-summary generator + freshness gate.
# Compose-time admission needs a per-module resource summary: the record
# capacities, channel buffers, instrument count and declared hardware target of
# every shipping module, in one place, kept in lockstep with the manifests. This
# GENERATES docs/architecture/resource_summary.md from the manifests and, in CI
# (`--check`), fails if the committed doc is stale — so the summary a deployment
# reads is always the one the modules actually declare.
set -u
here="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$here" || exit 1
DOC="docs/architecture/resource_summary.md"
mode="${1:---check}"

gen() {
  cat <<'HDR'
# Chronicle module resource summary

Generated by `tools/ci/resource-summary.sh` from the shipping
manifests — do not edit by hand; run the generator. Compose-time admission reads
these per-module declarations to decide whether a target can host a graph. Absolute
memory/step budgets and the constants behind these capacities live in
[`limit_register.md`](limit_register.md); the accounting instruments each module
emits are the baseline (14) plus its own, verified by
`tools/ci/accounting-order.sh`.

| Module | Target | Port | Dir | max_record (B) | buffer (B) | Instruments |
|---|---|---|---|---|---|---|
HDR
  for man in modules/app/*/manifest.toml; do
    m=$(basename "$(dirname "$man")")
    tgt=$(grep -oE 'hardware_targets *= *\[[^]]*\]' "$man" | grep -oE '"[a-z0-9_]+"' | tr -d '"' | paste -sd, -)
    # instrument count = entries in the metrics array
    nmet=$(awk '/metrics *= *\[/{g=1} g{n+=gsub(/"[^"]+"/,"&")} g&&/\]/{print n; exit}' "$man")
    # each port: name, direction, max_record, buffer_size
    awk -v mod="$m" -v tgt="$tgt" -v nm="$nmet" '
      /\[\[ports\]\]/{inport=1; name=dir=mr=bs=""}
      inport&&/name *=/{gsub(/.*= *"|".*/,""); name=$0}
      inport&&/direction *=/{gsub(/.*= *"|".*/,""); dir=$0}
      inport&&/max_record *=/{gsub(/[^0-9]/,"",$0); mr=$0}
      inport&&/buffer_size *=/{gsub(/[^0-9]/,"",$0); bs=$0; 
        printf "| %s | %s | %s | %s | %s | %s | %s |\n", mod, tgt, name, dir, mr, bs, nm; inport=0}
    ' "$man"
  done
  echo ""
  echo "Generated from \`modules/app/*/manifest.toml\`. Steady-state modules also"
  echo "declare a per-step budget of one record plus pending-output drain,"
  echo "and report \`work_units\` (VM instructions / stages / emissions consumed)."
}

if [ "$mode" = "--check" ]; then
  tmp=$(mktemp)
  gen > "$tmp"
  if ! diff -q "$tmp" "$DOC" >/dev/null 2>&1; then
    echo "  FAIL  resource-summary: $DOC is stale — run tools/ci/resource-summary.sh"
    diff "$DOC" "$tmp" 2>/dev/null | head -20
    rm -f "$tmp"; exit 1
  fi
  rm -f "$tmp"
  echo "  PASS  resource-summary: $DOC matches the manifests"
else
  mkdir -p "$(dirname "$DOC")"
  gen > "$DOC"
  echo "  wrote $DOC"
fi
